<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Application.Features</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="NJsonSchema" Version="11.6.1" />
    <PackageReference Include="NSwag.Annotations" Version="14.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\10-Application\10-Application.csproj" />
    <ProjectReference Include="..\13-Application.Ressources\13-Application.Ressources.csproj" />
    <ProjectReference Include="..\24-Infrastructure.ExternalAuth\24-Infrastructure.ExternalAuth.csproj" />
    <ProjectReference Include="..\99-Tools\99-Tools.csproj" />
  </ItemGroup>
</Project>
