name: ElectorCI - Build & Test (Frontend)

on:
  pull_request:
    types: [opened, closed]
    branches: [develop, qa, master]
    paths:
      - "src/front/web-client/**"
      - ".github/workflows/ElectorCI.BuildAndTest.Front.yml"

defaults:
  run:
    working-directory: src/front/web-client

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm
          cache-dependency-path: src/front/web-client/package-lock.json

      - name: Install dependencies
        run: npm ci

     # - name: Run unit tests
     #   run: npx ng test --no-watch

      - name: Build
        run: npx ng build --configuration production

      - name: Publish build output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-client-dist
          path: src/front/web-client/dist/**
          retention-days: 7
